# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: |
          markdown <- function(x, group = c("filename", "functions"), by = "line", ...) {
            if (length(x) == 0) {
              return(invisible(x))
            }
            group <- match.arg(group)

            df <- covr::tally_coverage(x, by = by)

            if (!NROW(df)) {
              return(invisible(x))
            }

            percents <- tapply(df$value, df[[group]], FUN = function(x) (sum(x > 0) / length(x)) * 100)

            overall_percentage <- covr::percent_coverage(df, by = by)

            paste0("|file|percents|\n|----|----|\n",
              paste0("|Overall|", format(overall_percentage, digits = 4), "%|\n"),
              paste0("|", names(percents), "|", format(percents, digits = 4), "%|", collapse = "\n"), "\n")
          }
          Sys.setenv(GITHUB_STEP_SUMMARY = paste0("COVERAGE_SUMMARY", markdown(covr::package_coverage())))
        shell: Rscript {0}
    
      - name: Adding markdown
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
        
      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
